disable_existing_loggers: false
formatters:
  detailed:
    format: '%(asctime)s [%(levelname)s] %(name)s [%(filename)s:%(lineno)d] %(message)s'
  json:
    (): pythonjsonlogger.jsonlogger.JsonFormatter
    format: '%(asctime)s %(name)s %(levelname)s %(message)s'
  standard:
    format: '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    formatter: standard
    level: INFO
    stream: ext://sys.stdout
  error_file:
    backupCount: 5
    class: logging.handlers.RotatingFileHandler
    filename: /var/log/qbtc/error.log
    formatter: json
    level: ERROR
    maxBytes: 52428800
  file:
    backupCount: 10
    class: logging.handlers.RotatingFileHandler
    filename: /var/log/qbtc/application.log
    formatter: detailed
    level: INFO
    maxBytes: 104857600
loggers:
  quantum:
    handlers:
    - console
    - file
    level: INFO
    propagate: false
  scripts:
    handlers:
    - console
    - file
    level: INFO
    propagate: false
  tools:
    handlers:
    - console
    - file
    level: INFO
    propagate: false
root:
  handlers:
  - console
  - error_file
  level: WARNING
version: 1
