providers:
  swarm:
    exposedByDefault: false
    watch: true
  docker:
    exposedByDefault: false
    watch: true
    network: dokploy-network
  file:
    directory: /etc/dokploy/traefik/dynamic
    watch: true

entryPoints:
  web:
    address: ':80'
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ':443'
    http3:
      advertisedPort: 443

api:
  insecure: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: admin@vigoleonrocks.com
      storage: /etc/dokploy/traefik/acme.json
      httpChallenge:
        entryPoint: web
